version: '3.5'

services:

  mysql-server:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - zbx_net
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:${TAG-latest}
    restart: unless-stopped
    networks:
      - zbx_net
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
      - ZBX_STARTREPORTWRITERS=2
      - ZBX_WEBSERVICEURL=http://zabbix-web-service:10053/report
      - ZBX_STARTVMWARECOLLECTORS=8
      - ZBX_VMWAREFREQUENCY=60
      - ZBX_VMWAREPERFFREQUENCY=60
      - ZBX_VMWARECACHESIZE=256M
      - ZBX_VMWARETIMEOUT=120
      - ZBX_CACHESIZE=256M
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ./script:/usr/lib/zabbix/alertscripts:ro

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:${TAG-latest}
    restart: unless-stopped
    networks:
      - zbx_net
    ports:
      - 80:8080
      - 443:8443
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:${TAG-latest}
    restart: unless-stopped
    networks:
      - zbx_net
    ports:
      - 10052:10052
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 

  zabbix-web-service:
    image: zabbix/zabbix-web-service:${TAG-latest}
    restart: unless-stopped
    environment:
      - ZBX_ALLOWEDIP=zabbix-server-mysql
    networks:
      - zbx_net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 

networks:
  zbx_net:
    ipam:
      config:
        - subnet: 10.6.0.0/24
          gateway: 10.6.0.1
